USE db_resteco;

DROP PROCEDURE IF EXISTS MOSTRARTIPOCLIENTE;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOCLIENTE()
	BEGIN
		SELECT * FROM tb_tipo_cliente;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOCOMUNICACION;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOCOMUNICACION()
	BEGIN
		SELECT * FROM tb_tipo_comunicacion;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPODOMICILIO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPODOMICILIO()
	BEGIN
		SELECT * FROM tb_tipo_domicilio;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOPERSONA;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOPERSONA()
	BEGIN
		SELECT * FROM tb_tipo_persona;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOUSUARIO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOUSUARIO()
	BEGIN
		SELECT * FROM tb_tipo_usuario;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOCOMPROBANTE;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOCOMPROBANTE(
		IN _inTipoDetalle INT)
	BEGIN
		SELECT * FROM tb_tipo_comprobante
		WHERE intTipoDetalle = _inTipoDetalle;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOCODIGOPRODUCTO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOCODIGOPRODUCTO()
	BEGIN
		SELECT * FROM tb_tipo_codigo_producto;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOMONEDA;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOMONEDA()
	BEGIN
		SELECT * FROM tb_tipo_moneda;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOCLIENTE;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOCLIENTE()
	BEGIN
		SELECT * FROM tb_tipo_cliente;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOPAGO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOPAGO()
	BEGIN
		SELECT * FROM tb_tipo_pago;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARTIPOVENTA;
DELIMITER $$
	CREATE PROCEDURE MOSTRARTIPOVENTA()
	BEGIN
		SELECT * FROM tb_tipo_venta;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARSUCURSAL;
DELIMITER $$
	CREATE PROCEDURE MOSTRARSUCURSAL()
	BEGIN
		SELECT * FROM tb_sucursal;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARDEPARTAMENTO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARDEPARTAMENTO()
	BEGIN
		SELECT * FROM tb_departamentos;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARPROVINCIA;
DELIMITER $$
	CREATE PROCEDURE MOSTRARPROVINCIA(
		IN _intIdDepartamento INT
		)
	BEGIN
		SELECT * FROM tb_provincias
		WHERE intIdDepartamento = _intIdDepartamento;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS MOSTRARDISTRITO;
DELIMITER $$
	CREATE PROCEDURE MOSTRARDISTRITO(
		IN _intIdProvincia INT
		)
	BEGIN
		SELECT * FROM tb_distritos
		WHERE intIdProvincia = _intIdProvincia;
    END 
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS SELECCIONARPROVINCIA;
DELIMITER $$
	CREATE PROCEDURE SELECCIONARPROVINCIA(
		IN _intIdDepartamento INT
		)
	BEGIN
		SELECT * FROM tb_provincias
		WHERE intIdDepartamento = _intIdDepartamento
		LIMIT 1;
    END 
$$
DELIMITER ;